// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC5TMBPw4Al_NzKHg4bzmu9XHk-54FsJk',
    appId: '1:895096193749:web:ca3da71ed76f709694985c',
    messagingSenderId: '895096193749',
    projectId: 'clg-app-5e72d',
    authDomain: 'clg-app-5e72d.firebaseapp.com',
    storageBucket: 'clg-app-5e72d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLa3kMjxIeClQb2R7pIbhG-pnqDHrhwsk',
    appId: '1:895096193749:android:3d4bd5f1c810303294985c',
    messagingSenderId: '895096193749',
    projectId: 'clg-app-5e72d',
    storageBucket: 'clg-app-5e72d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTDvTnZPsdCpwrKD_BdByTd2f8VQmXlg4',
    appId: '1:895096193749:ios:b596230e0af34fc894985c',
    messagingSenderId: '895096193749',
    projectId: 'clg-app-5e72d',
    storageBucket: 'clg-app-5e72d.firebasestorage.app',
    iosBundleId: 'com.example.clgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTDvTnZPsdCpwrKD_BdByTd2f8VQmXlg4',
    appId: '1:895096193749:ios:b596230e0af34fc894985c',
    messagingSenderId: '895096193749',
    projectId: 'clg-app-5e72d',
    storageBucket: 'clg-app-5e72d.firebasestorage.app',
    iosBundleId: 'com.example.clgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC5TMBPw4Al_NzKHg4bzmu9XHk-54FsJk',
    appId: '1:895096193749:web:d19c9a347b0b957594985c',
    messagingSenderId: '895096193749',
    projectId: 'clg-app-5e72d',
    authDomain: 'clg-app-5e72d.firebaseapp.com',
    storageBucket: 'clg-app-5e72d.firebasestorage.app',
  );
}
